---
- name : ios module
  hosts : cisco
  gather_facts : false
  connection : network_cli
  tasks :
    - name : "Parse text from file"
      ios_command :
        commands :
          - show version
          - show clock
      register : value
    - debug : var=value.stdout_lines
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
